apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: carloselpapa10/demo:1.0
        ports:
        - name: demo-port
          containerPort: 8080
  
