apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - echo hello world;sleep 3600
    image: busybox
    name: busybox
    resources:
      limits:
        cpu: "750m"
        memory: "950Mi"
      requests:
        cpu: "700m"
        memory: "800Mi"
