apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - echo hello world;sleep 3600
    image: busybox
    name: busybox1
    resources:
      limits:
        cpu: "1"
        memory: "1500Mi"
      requests:
        cpu: "1"
        memory: "1000Mi"
  - args:
    - /bin/sh
    - -c
    - echo hello world2;sleep 3600
    image: busybox
    name: busybox2
    resources:
      limits:
        cpu: "1"
        memory: "700Mi"
      requests:
        cpu: "1"
        memory: "500Mi"
