apiVersion: v1
kind: List
items:
- apiVersion: scheduling.k8s.io/v1
  kind: PriorityClass
  metadata:
    name: high
  value: 1000000
  globalDefault: false
  description: "This priority class should be used for high priority pods only."
- apiVersion: scheduling.k8s.io/v1
  kind: PriorityClass
  metadata: 
    name: medium
  value: 800000
  globalDefault: false
  description: "This priority class should be used for medium priority  pods only."
- apiVersion: scheduling.k8s.io/v1
  kind: PriorityClass
  metadata: 
    name: low
  value: 500000
  globalDefault: true
  description: "This priority class should be used for low priority  pods only."
