apiVersion: v1
kind: Pod
metadata:
  labels:
    app: multi-container
  name: multi-container
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - echo hello world;sleep 3600
    image: busybox
    name: busybox1
  - args:
    - /bin/sh
    - -c
    - echo hello world;sleep 3600
    image: busybox
    name: busybox2
  restartPolicy: Never
