apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: memory-demo-toobig
  name: memory-demo-toobig
  namespace: mem-example
spec:
  containers:
  - name: memory-demo-3-ctr
    image: polinux/stress
    resources:
      limits:
        memory: "1000Gi"
      requests:
        memory: "1000Gi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
