apiVersion: v1
kind: Pod
metadata:
  name: "demo"
  labels:
    app: demo
spec:
  containers:
    - name: demo
      image: "carloselpapa10/demo:latest"
      ports:
        - name: http
          containerPort: 8080
